import { useState } from "react";
import { ArrowDown, ArrowRight, AudioLines, Check, ChevronRight, FileText, Menu, Mic, MoveRight, Pause, Repeat2, TrendingUp, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AnalysisPreview, VoiceMark } from "./landing/analysis-preview";

const features = [
  { icon: TrendingUp, name: "Pace", text: "Find a rhythm people can follow.", visual: "pace", value: "142", unit: "words / min" },
  { icon: Pause, name: "Pauses", text: "Make a little silence work for you.", visual: "pauses", value: "1.8", unit: "seconds" },
  { icon: AudioLines, name: "Filler words", text: "Notice the habits you don’t hear.", visual: "fillers", value: "um", unit: "uh" },
  { icon: AudioLines, name: "Vocal variation", text: "Bring your ideas to life with your voice.", visual: "pitch", value: "", unit: "" },
  { icon: FileText, name: "Transcript", text: "See your words in a new light.", visual: "transcript", value: "", unit: "" },
];
function FeatureVisual({ type, value, unit }: { type: string; value: string; unit: string }) {
  if (type === "pitch") return <svg className="feature-pitch" viewBox="0 0 170 64" aria-hidden="true"><path d="M0 42 C12 42 12 13 25 13 S38 52 51 52 S64 25 76 25 S91 40 103 40 S120 10 132 10 S149 34 170 26" /></svg>;
  if (type === "transcript") return <div className="feature-transcript" aria-hidden="true"><span>The thing about</span><span>creating <mark>um</mark> content</span><span>is just getting started.</span></div>;
  if (type === "fillers") return <div className="feature-fillers" aria-hidden="true"><span>{value}</span><span>{unit}</span><span>like</span></div>;
  return <div className={`feature-number ${type}`} aria-hidden="true"><strong>{value}</strong><span>{unit}</span>{type === "pauses" && <div className="pause-dashes"><i /><i /><i /><i /><i /></div>}</div>;
}
export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [dialog, setDialog] = useState<"start" | "signin" | null>(null);
  const start = () => setDialog("start");
  const closeMenu = () => setMenuOpen(false);
  return <div className="landing-page">
    <header className="site-header"><div className="site-nav page-width"><a href="#" className="brand" aria-label="Cadence home"><VoiceMark /><span>cadence<span className="brand-period">.</span></span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#features">Features</a></nav><div className="nav-actions"><Button variant="ghost" className="sign-in" onClick={() => setDialog("signin")}>Sign in</Button><Button variant="speaking" className="nav-cta" onClick={start}>Start speaking <ArrowRight /></Button><Button variant="ghost" size="icon" className="menu-toggle" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div></div>{menuOpen && <nav className="mobile-nav page-width" aria-label="Mobile navigation"><a href="#how-it-works" onClick={closeMenu}>How it works <ChevronRight size={16} /></a><a href="#features" onClick={closeMenu}>Features <ChevronRight size={16} /></a><Button variant="ghost" onClick={() => { closeMenu(); setDialog("signin"); }}>Sign in <ArrowRight /></Button></nav>}</header>
    <main>
      <section className="hero page-width" aria-labelledby="hero-title"><div className="hero-intro"><div className="eyebrow hero-eyebrow"><span className="status-dot" /> YOUR VOICE. ONLY BETTER.</div><h1 id="hero-title">Become a better speaker<br className="desktop-break" /> by actually seeing<br className="desktop-break" /> <span>how you speak.</span></h1><p className="hero-description">Record yourself, get clear feedback on your delivery, and practice<br className="desktop-break" /> the skills that make people want to keep listening.</p><div className="hero-actions"><Button variant="speaking" size="cta" onClick={start}>Start speaking <ArrowRight /></Button><Button variant="quiet" size="cta" asChild><a href="#how-it-works">See how it works <ArrowDown size={15} /></a></Button></div><p className="hero-note">A clearer voice starts with a little awareness.</p></div><div className="hero-product"><AnalysisPreview /></div><div className="creator-note"><span>FOR THE MOMENTS YOUR VOICE MATTERS</span><div><span>Content creators</span><i /><span>Personal brands</span><i /><span>Everyday conversations</span></div></div></section>
      <section className="problem-section" aria-labelledby="problem-title"><div className="page-width problem-grid"><div><div className="eyebrow section-eyebrow">A LITTLE AWARENESS CHANGES EVERYTHING</div><h2 id="problem-title">You can hear yourself.<br />But you can’t always hear<br /><span>what you’re doing wrong.</span></h2></div><div className="problem-copy"><p>When you’re speaking, it’s hard to notice your own habits.</p><p>You rush through your best idea. Fill a little silence with “um” and “uh”. Settle into the same tone. Your message is there. Your delivery gets in the way.</p><p className="problem-conclusion">Make those patterns visible.<br /><span>Then make your next take better.</span></p></div></div></section>
      <section id="how-it-works" className="how-section page-width" aria-labelledby="how-title"><div className="section-heading"><div className="eyebrow section-eyebrow">THE PRACTICE LOOP</div><h2 id="how-title">Speak. Analyze. Improve.<br /><span>And go again.</span></h2><p>Progress doesn’t need to be complicated. Just consistent.</p></div><div className="steps-grid"><div className="step"><div className="step-top"><span>01</span><Mic size={21} /><MoveRight className="step-arrow" size={22} /></div><div className="step-graphic speak-graphic" aria-hidden="true">{Array.from({ length: 17 }, (_, i) => <i key={i} />)}</div><h3>Speak</h3><p>Record yourself talking naturally.</p><span className="step-detail">An idea. A story. Your next video.</span></div><div className="step"><div className="step-top"><span>02</span><AudioLines size={21} /><MoveRight className="step-arrow" size={22} /></div><div className="step-graphic analyze-graphic" aria-hidden="true"><span>142 <small>WPM</small></span><div><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><h3>Analyze</h3><p>See measurable patterns in your delivery.</p><span className="step-detail">Less guessing. More understanding.</span></div><div className="step"><div className="step-top"><span>03</span><Repeat2 size={21} /></div><div className="step-graphic improve-graphic" aria-hidden="true"><TrendingUp /><span>A little better,<br />every time.</span></div><h3>Improve</h3><p>Practice one specific skill and try again.</p><span className="step-detail">Small changes. A stronger voice.</span></div></div></section>
      <section id="features" className="features-section" aria-labelledby="features-title"><div className="page-width"><div className="features-heading"><div><div className="eyebrow section-eyebrow">GO BEYOND “THAT SOUNDED OKAY”</div><h2 id="features-title">Understand your delivery.<br /><span>One detail at a time.</span></h2></div><p>Clear signals. Practical feedback.<br />A better feel for how you come across.</p></div><div className="features-grid">{features.map(({ icon: Icon, name, text, visual, value, unit }) => <article className="feature" key={name}><div className="feature-icon"><Icon size={18} /></div><FeatureVisual type={visual} value={value} unit={unit} /><h3>{name}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="final-section page-width" aria-labelledby="final-title"><VoiceMark className="final-mark" /><div className="eyebrow">YOUR VOICE IS WORTH WORKING ON</div><h2 id="final-title">Your next conversation is<br /><span>your next practice session.</span></h2><Button variant="speaking" size="cta" onClick={start}>Start speaking <ArrowRight /></Button><p>Speak. Analyze. Improve. Repeat.</p></section>
    </main>
    <footer className="site-footer page-width"><a href="#" className="brand footer-brand"><VoiceMark /><span>cadence<span className="brand-period">.</span></span></a><span>A little more clarity. A little more you.</span><span className="footer-copyright">© 2026 Cadence</span></footer>
    <Dialog open={dialog !== null} onOpenChange={(open) => { if (!open) setDialog(null); }}><DialogContent className="prototype-dialog"><div className="dialog-mark"><VoiceMark /></div><DialogHeader><DialogTitle>{dialog === "signin" ? "Your voice. Your space." : "A better voice is on the way."}</DialogTitle><DialogDescription>{dialog === "signin" ? "Sign-in will be available when Cadence launches. There’s no account to create just yet." : "Cadence is a preview of what’s coming. Recording and speaking feedback aren’t available yet."}</DialogDescription></DialogHeader><div className="dialog-detail"><Check size={16} /><span>For now, explore a sample speaking analysis.</span></div><Button variant="speaking" size="cta" asChild><a href="#analysis-preview" onClick={() => setDialog(null)}>Explore the preview <ArrowRight /></a></Button></DialogContent></Dialog>
  </div>;
}
